In [2]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [ ]:
array=np.empty((2,2))
print(array)



[[3.25065588e-315 0.00000000e+000]
 [6.59737730e-310 0.00000000e+000]]


2. Initialize an all one array with size 4X2.

In [ ]:
array=np.ones((4,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
array=np.full((2,2),7)
print(array)

[[7 7]
 [7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
a =np.array([[3,4,5,6],[7,8,2,3]])
zeros_arr=np.zeros_like(a)
print(zeros_arr)


[[0 0 0 0]
 [0 0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
#question no five
a=np.array([[4,5,6,7,8],[2,9,10,12,6]])
ones_arr=np.ones_like(a)
print(ones_arr)

[[1 1 1 1 1]
 [1 1 1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list=[1,2,3,4]
new_array=np.array(new_list)
print(new_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
array=np.arange(10,49)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
array=np.arange(9)
matrix=array.reshape(3,3)
print(array)


[0 1 2 3 4 5 6 7 8]


Create a 3X3 identity matrix.{Hint:np.eye()}


In [ ]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array = np.random.random(30)

mean_value = random_array.mean()

print("Random Array", random_array)
print("Mean of the array:", mean_value)

Random Array [0.74628691 0.210507   0.35738627 0.66844119 0.4020263  0.20661228
 0.84006561 0.53276163 0.04324741 0.64140123 0.84620874 0.89450013
 0.91503966 0.05234704 0.45369642 0.28750845 0.05376462 0.28413218
 0.72091214 0.01017374 0.34719864 0.74883144 0.66245024 0.52122814
 0.47437153 0.28354658 0.71135767 0.32865471 0.88885852 0.80978751]
Mean of the array: 0.49811013093947726


Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_array = np.random.random((10, 10))

min_value = random_array.min()
max_value = random_array.max()

print("Random ", random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Random  [[0.2225762  0.72977397 0.59745115 0.21219052 0.92582475 0.16014814
  0.02215994 0.4754802  0.78140556 0.29807198]
 [0.22729247 0.84154132 0.28612121 0.70991526 0.69990906 0.93001216
  0.6048479  0.02350921 0.71058085 0.51584481]
 [0.28995084 0.13876891 0.54763032 0.72059245 0.02517459 0.04812949
  0.42205131 0.67082128 0.94505693 0.85196975]
 [0.62883498 0.75694102 0.1960144  0.378521   0.5687781  0.35554431
  0.59810966 0.49089287 0.67532848 0.01110611]
 [0.43004459 0.84791001 0.84426583 0.34223556 0.20234861 0.56489982
  0.41026309 0.76962978 0.14041141 0.97163751]
 [0.03948804 0.5489353  0.08926427 0.86465081 0.38488355 0.93486555
  0.29140043 0.33605682 0.03000401 0.0304227 ]
 [0.39719365 0.34043323 0.44672833 0.98796409 0.39408812 0.23350475
  0.17177844 0.09631611 0.32498549 0.86575639]
 [0.5034828  0.49669909 0.38416078 0.09445068 0.78893318 0.07877812
  0.94429097 0.43298252 0.67978227 0.62010351]
 [0.72064908 0.59023351 0.79360987 0.34990767 0.21845569 0.39499123
  0.

Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Reverse an array arr = [1,2,0,0,4,0].


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])

reversed_arr = arr[::-1]
print(reversed_arr)

Create a 2d array with 1 on border and 0 inside.

In [ ]:
rows, cols = 5, 5
array = np.zeros((rows, cols), dtype=int)

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [3]:

x = np.array([[1,2],
              [3,5]])

y = np.array([[5,6],
              [7,8]])

result = x + y
print(result)

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [5]:
x = np.array([[1,2],
              [3,5]])

y = np.array([[5,6],
              [7,8]])
result = x - y
print(result)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [4]:
x = np.array([[1,2],
              [3,5]])

y = np.array([[5,6],
              [7,8]])
result = x * 3
print(result)

[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [6]:

x = np.array([[1,2],
              [3,5]])

y = np.array([[5,6],
              [7,8]])
result = x ** 2
print(result)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [10]:
v = np.array([9, 10])
w = np.array([11, 12])

result = np.dot(v, w)
print(result)

219


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [11]:
v = np.array([9, 10])
w = np.array([11, 12])

result = np.vstack((x, y))
print(result)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1,2],[3,5]])
v = np.array([9,10])

result = np.concatenate((x, v), axis=0)
print(result)



This will give an ERROR.x is a 2D array with shape (2, 2)
v is a 1D array with shape (2, )

NumPy cannot concatenate arrays along a given axis when their dimensions do not match



Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.

In [12]:
A = np.array([[3, 4],
              [7, 8]])

In [13]:
A_inv = np.linalg.inv(A)
print("A inverse:")
print(A_inv)

A inverse:
[[-2.    1.  ]
 [ 1.75 -0.75]]


In [14]:
result = np.dot(A, A_inv)
print("A * A_inv:")
print(result)

A * A_inv:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [15]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

AB = np.dot(A, B)
print("AB =")
print(AB)

AB =
[[23 13]
 [51 29]]


In [16]:
BA = np.dot(B, A)
print("BA =")
print(BA)

BA =
[[36 44]
 [13 16]]


3. Prove (AB)

T = BTAT

In [17]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])
AB = np.dot(A, B)
AB_T = AB.T
print("(AB)^T =")
print(AB_T)


(AB)^T =
[[23 51]
 [13 29]]


In [18]:
B_T = B.T
A_T = A.T
BT_AT = np.dot(B_T, A_T)
print("B^T * A^T =")
print(BT_AT)

B^T * A^T =
[[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [19]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution [x, y, z] =")
print(X)

Solution [x, y, z] =
[ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [21]:
import time

# Using Python Lists
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()

# Element-wise addition using list comprehension
list_sum = [list1[i] + list2[i] for i in range(size)]

end_time = time.time()
print("Time taken using Python lists: {:.5f} seconds".format(end_time - start_time))

# Using NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()

# Element-wise addition using NumPy
arr_sum = arr1 + arr2

end_time = time.time()
print("Time taken using NumPy arrays: {:.5f} seconds".format(end_time - start_time))

Time taken using Python lists: 0.12430 seconds
Time taken using NumPy arrays: 0.00407 seconds


Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [23]:
import time

# Using Python Lists
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()

# Element-wise multiplication using list comprehension
list_mul = [list1[i] * list2[i] for i in range(size)]

end_time = time.time()
print("Time taken using Python lists: {:.5f} seconds".format(end_time - start_time))

# Using NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()

# Element-wise multiplication using NumPy
arr_mul = arr1 * arr2

end_time = time.time()
print("Time taken using NumPy arrays: {:.5f} seconds".format(end_time - start_time))

Time taken using Python lists: 0.11401 seconds
Time taken using NumPy arrays: 0.00221 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time

size = 1000000

# Using Python Lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()

# Dot product using sum of element-wise multiplication
dot_list = sum(list1[i] * list2[i] for i in range(size))

end_time = time.time()
print("Dot product using Python lists:", dot_list)
print("Time taken using Python lists: {:.5f} seconds".format(end_time - start_time))

# Using NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()

# Dot product using NumPy
dot_numpy = np.dot(arr1, arr2)

end_time = time.time()
print("Dot product using NumPy arrays:", dot_numpy)
print("Time taken using NumPy arrays: {:.5f} seconds".format(end_time - start_time))

4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time
import random

size = 1000
# Using Python Lists
# Create two 1000x1000 matrices with random integers
matrix1 = [[random.randint(0, 10) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(0, 10) for _ in range(size)] for _ in range(size)]

start_time = time.time()

# Matrix multiplication using nested loops
result_list = [[0 for _ in range(size)] for _ in range(size)]
for i in range(size):
    for j in range(size):
        for k in range(size):
            result_list[i][j] += matrix1[i][k] * matrix2[k][j]

end_time = time.time()
print("Time taken using Python lists: {:.5f} seconds".format(end_time - start_time))

# Using NumPy Arrays
arr1 = np.random.randint(0, 11, (size, size))
arr2 = np.random.randint(0, 11, (size, size))

start_time = time.time()

# Matrix multiplication using NumPy
result_numpy = np.dot(arr1, arr2)

end_time = time.time()
print("Time taken using NumPy arrays: {:.5f} seconds".format(end_time - start_time))